### ISSUE TITLE
Mastodon on roadmap

### ISSUE THREAD

**Issue by robsonsobral** [TwidereProject/TwidereX-Android#1]
Hi, what's the plan about the implementation of Mastodon? Soon? Or after to finish Twitter features?

Thank you!

**Comment by barudaret** [comment]
My vote fwiw (as someone who doesn't really use twitter) goes to the latter.  Since masto also offers pretty much all the same features, and since there are great masto apps already out there such as Husky, it is more beneficial in the short term to have a good FOSS twitter client, than to have a half-functional masto app.

**Comment by Tedko** [comment]
Hi all.
We definitely are going to support Fediverse soon. Right now we don't have enough man-power and try to deliver the twitter ver for testing the stability etc 1st.

**Comment by Tlaster** [comment]
Mastodon support is here now! Check out the 1.1.0 release https://github.com/TwidereProject/TwidereX-Android/releases/tag/1.1.0
