### ISSUE TITLE
[BUG] "Unparseable date" error

### ISSUE THREAD

**Issue by Occhioverde** [TwidereProject/TwidereX-Android#402]
**Describe the bug**
For a few days now, the "Unparseable date" error (visible in the first attached screenshot) has been appearing whenever TwidereX is started after clicking on a Twitter URL, making it impossible to view any posts you try to open.
If, on the other hand, the tweet is opened directly from the TwidereX timeline, the post is loaded correctly, but the error is still displayed below in place of the various replies.

**To Reproduce**

***Case 1:***
1. Set TwidereX as the default app to oper Twitter links
2. Click on a tweet URL (like https://twitter.com/Linux/status/936877536780283905)
3. Notice the "Unparseable date" error

***Case 2:***
1. Open a post in your timeline
2. Notice the "Unparseable date" error under the tweet, in place of the replies

**Expected behavior**
The error should not occour

**Screenshots**
***Case 1:***
![Screenshot_20220128-201037](https://user-images.githubusercontent.com/18429412/151608121-d5d9f4f5-0679-47d2-9b48-eec72786f33e.jpg)

***Case 2:***
![Screenshot_20220128-201136](https://user-images.githubusercontent.com/18429412/151608172-3bee2b86-d17e-41eb-b6f5-81bb664bdb3e.jpg)

**Smartphone (please complete the following information):**
 - Device: Huawei BAH2-W19
 - OS: Android 8.0.0
 - Variant: F-Droid
 - Version: 1.5.1

**Comment by kuoirad** [comment]
I ran into this problem today while trying to use Nitter to improve the threading while I'm trying out Twidere X.

Device: Pixel 3
OS: Android 12.0
Variant: Play Store
Version: 1.5.1

**Comment by fishy** [comment]
I'm seeing the same issue with nitter

**Comment by ix5** [comment]
Seeing a new issue since at least August 25, 2022

`Unparseable date: "Sep 2, 2022 · 10:04 AM UTC"` (at least I think it's an interpunct: `·`)

Example: https://twitter.com/Jack_Watling/status/1565640613604855808
![photo_2022-09-02_15-26-43-resized](https://user-images.githubusercontent.com/10212877/188156084-51ac0166-3a90-4407-a637-94dd55f78cda.jpg)


This format _should_ be covered by `"MMM d, yyyy · H:mm aaa ZZZZ"` as in https://github.com/TwidereProject/TwidereX-Android/pull/439/commits/40e25b9b9692ccbec1f390a57d631fcf828d1b14#diff-32d0f889fce363f5c993de2da63cbc2cd528f1780344652f3b5d300327acbf3fR38

Also using nitter. Turning off nitter integration makes this bug go away.

**Comment by Idesmi** [comment]
This issue is not fixed.
